
////////////////////////////////////////////////////////////////////////////////
// Copyright (c) 2007 IBM Corporation.
// All rights reserved. This program and the accompanying materials
// are made available under the terms of the Eclipse Public License v1.0
// which accompanies this distribution, and is available at
// http://www.eclipse.org/legal/epl-v10.html
//
//Contributors:
//    Stan Sutton (suttons@us.ibm.com) - initial API and implementation
//    Robert Fuhrer (rfuhrer@watson.ibm.com)
////////////////////////////////////////////////////////////////////////////////

package org.eclipse.imp.prefspecs.parser;

public interface PrefspecsParsersym {
    public final static int
      TK_COMMA = 7,
      TK_DOT = 18,
      TK_SEMICOLON = 1,
      TK_PLUS = 35,
      TK_MINUS = 36,
      TK_LEFTPAREN = 61,
      TK_RIGHTPAREN = 62,
      TK_LEFTBRACE = 3,
      TK_RIGHTBRACE = 2,
      TK_PACKAGE = 37,
      TK_PAGE = 19,
      TK_TABS = 38,
      TK_FIELDS = 20,
      TK_CONDITIONALS = 39,
      TK_CHOICETYPE = 21,
      TK_CUSTOM = 40,
      TK_DETAILS = 41,
      TK_DEFAULT = 9,
      TK_CONFIGURATION = 10,
      TK_INSTANCE = 11,
      TK_PROJECT = 12,
      TK_IN = 42,
      TK_OUT = 43,
      TK_BOOLEAN = 22,
      TK_COLOR = 23,
      TK_COMBO = 24,
      TK_DOUBLE = 25,
      TK_DIRLIST = 26,
      TK_FILE = 27,
      TK_FONT = 28,
      TK_INT = 29,
      TK_RADIO = 30,
      TK_STRING = 31,
      TK_BOLD = 44,
      TK_COLUMNS = 32,
      TK_DEFVALUE = 4,
      TK_EMPTYALLOWED = 33,
      TK_HASSPECIAL = 8,
      TK_ISEDITABLE = 45,
      TK_ISREMOVABLE = 46,
      TK_ITALIC = 47,
      TK_LABEL = 48,
      TK_NORMAL = 49,
      TK_RANGE = 13,
      TK_TOOLTIP = 50,
      TK_TYPE = 51,
      TK_VALIDATOR = 52,
      TK_VALUES = 53,
      TK_TRUE = 14,
      TK_FALSE = 15,
      TK_ON = 54,
      TK_OFF = 55,
      TK_WITH = 56,
      TK_AGAINST = 57,
      TK_IF = 58,
      TK_UNLESS = 59,
      TK_EOF_TOKEN = 60,
      TK_SINGLE_LINE_COMMENT = 63,
      TK_IDENTIFIER = 16,
      TK_INTEGER = 5,
      TK_STRING_LITERAL = 6,
      TK_DECIMAL = 17,
      TK_DOTS = 34,
      TK_ERROR_TOKEN = 64;

    public final static String orderedTerminalSymbols[] = {
                 "",
                 "SEMICOLON",
                 "RIGHTBRACE",
                 "LEFTBRACE",
                 "DEFVALUE",
                 "INTEGER",
                 "STRING_LITERAL",
                 "COMMA",
                 "HASSPECIAL",
                 "DEFAULT",
                 "CONFIGURATION",
                 "INSTANCE",
                 "PROJECT",
                 "RANGE",
                 "TRUE",
                 "FALSE",
                 "IDENTIFIER",
                 "DECIMAL",
                 "DOT",
                 "PAGE",
                 "FIELDS",
                 "CHOICETYPE",
                 "BOOLEAN",
                 "COLOR",
                 "COMBO",
                 "DOUBLE",
                 "DIRLIST",
                 "FILE",
                 "FONT",
                 "INT",
                 "RADIO",
                 "STRING",
                 "COLUMNS",
                 "EMPTYALLOWED",
                 "DOTS",
                 "PLUS",
                 "MINUS",
                 "PACKAGE",
                 "TABS",
                 "CONDITIONALS",
                 "CUSTOM",
                 "DETAILS",
                 "IN",
                 "OUT",
                 "BOLD",
                 "ISEDITABLE",
                 "ISREMOVABLE",
                 "ITALIC",
                 "LABEL",
                 "NORMAL",
                 "TOOLTIP",
                 "TYPE",
                 "VALIDATOR",
                 "VALUES",
                 "ON",
                 "OFF",
                 "WITH",
                 "AGAINST",
                 "IF",
                 "UNLESS",
                 "EOF_TOKEN",
                 "LEFTPAREN",
                 "RIGHTPAREN",
                 "SINGLE_LINE_COMMENT",
                 "ERROR_TOKEN"
             };

    public final static int numTokenKinds = orderedTerminalSymbols.length;
    public final static boolean isValidForParser = true;
}
